#!/usr/bin/env python3
"""
Template build script for Run the Docs animation HTML.

USAGE:
1. Copy this file to series/<name>/production/ep<NN>/build.py
2. Run after tts.py: python3 build.py
3. Reads timing.json (from tts.py)
4. Generates animation.html with TOTAL_DURATION and TIMING baked in

The HTML will contain:
- const TOTAL_DURATION = <value from timing.json>
- const TIMING = [...segments from timing.json...]
"""

import json
import sys

# Read timing.json (generated by tts.py)
try:
    with open('timing.json', 'r') as f:
        timing = json.load(f)
except FileNotFoundError:
    print("ERROR: timing.json not found. Run tts.py first.")
    sys.exit(1)

TOTAL_DURATION = timing['total_duration']
TIMING = timing['segments']

print(f"Building animation.html with TOTAL_DURATION={TOTAL_DURATION}s")
print(f"Total frames: {timing['total_frames_30fps']} @ 30fps")

# === EDIT BELOW: Your animation code ===
js = f'''
const W = 1920, H = 1080, CX = 960, CY = 540;

// Brand colors (from STYLE_GUIDE.md)
const BG = '#0a0a0a';
const GRAD1 = '#1a1a2e';
const GRAD2 = '#16213e';
const ACCENT = '#0f3460';
const HIGHLIGHT = '#e94560';
const TEXT = '#eee';
const CODE_BG = '#141423';
const CODE_TEXT = '#90ee90';
const BORDER = '#444';

const canvas = document.getElementById('c');
const ctx = canvas.getContext('2d');

// EXACT timing from Kokoro TTS
const TIMING = {json.dumps(TIMING, indent=2)};

// TOTAL_DURATION from TTS: voice + outro buffer
const TOTAL_DURATION = {TOTAL_DURATION};

// Easing functions for smooth animations
const ease = {{
  out: function(t) {{ return 1 - Math.pow(1-t, 3); }},
  inOut: function(t) {{ return t < 0.5 ? 4*t*t*t : 1-Math.pow(-2*t+2,3)/2; }},
  spring: function(t) {{
    if(t===0) return 0; if(t===1) return 1;
    const c4 = (2*Math.PI)/2.5;
    return Math.pow(2,-10*t)*Math.sin((t*10-0.75)*c4)+1;
  }},
}};

// Segment: ease from start time to end time
function seg(t, start, end) {{
  return Math.max(0, Math.min(1, (t - start) / (end - start)));
}}

// Draw rounded rectangle
function roundRect(ctx, x, y, w, h, r) {{
  ctx.beginPath();
  ctx.moveTo(x+r, y); ctx.lineTo(x+w-r, y);
  ctx.quadraticCurveTo(x+w, y, x+w, y+r);
  ctx.lineTo(x+w, y+h-r);
  ctx.quadraticCurveTo(x+w, y+h, x+w-r, y+h);
  ctx.lineTo(x+r, y+h);
  ctx.quadraticCurveTo(x, y+h, x, y+h-r);
  ctx.lineTo(x, y+r);
  ctx.quadraticCurveTo(x, y, x+r, y);
  ctx.closePath();
}}

// Convert hex color to rgba
function hexToRgba(hex, a) {{
  const r = parseInt(hex.slice(1,3),16);
  const g = parseInt(hex.slice(3,5),16);
  const b = parseInt(hex.slice(5,7),16);
  return 'rgba('+r+','+g+','+b+','+a+')';
}}

// Set font (size + weight)
function setFont(ctx, size, weight) {{
  weight = weight || '400';
  ctx.font = weight + ' ' + size + 'px -apple-system, BlinkMacSystemFont, sans-serif';
}}

function renderFrame(frameNum) {{
  const t = frameNum / 30;  // Convert frame number to seconds
  
  // Fill background
  ctx.fillStyle = BG;
  ctx.fillRect(0, 0, W, H);
  
  // === YOUR ANIMATION CODE HERE ===
  // Example: fade in title at TIMING[0].start
  const t0Start = TIMING[0].start;
  const t0End = TIMING[0].end;
  const titleAlpha = ease.out(seg(t, t0Start, t0Start + 0.3)) * (1 - ease.out(seg(t, t0End, t0End + 0.2)));
  
  if(titleAlpha > 0) {{
    ctx.save();
    ctx.globalAlpha = titleAlpha;
    setFont(ctx, 72, '700');
    ctx.fillStyle = HIGHLIGHT;
    ctx.textAlign = 'center';
    ctx.textBaseline = 'middle';
    ctx.fillText('Your Title Here', CX, CY);
    ctx.restore();
  }}
  
  // Example: show content during sentences
  for(let i = 0; i < TIMING.length; i++) {{
    const seg_i = TIMING[i];
    const sceneAlpha = ease.out(seg(t, seg_i.start, seg_i.start + 0.2)) * 
                       (1 - ease.out(seg(t, seg_i.end, seg_i.end + 0.2)));
    if(sceneAlpha > 0) {{
      ctx.save();
      ctx.globalAlpha = sceneAlpha;
      setFont(ctx, 48, '400');
      ctx.fillStyle = TEXT;
      ctx.textAlign = 'center';
      ctx.textBaseline = 'middle';
      ctx.fillText(seg_i.text, CX, CY + 100);
      ctx.restore();
    }}
  }}
  // === END YOUR CODE ===
}}

window.renderFrame = renderFrame;
'''
# === END EDIT ===

html = f'''<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=JetBrains+Mono:wght@400;500;600;700&display=swap" rel="stylesheet">
<style>
* {{ margin: 0; padding: 0; box-sizing: border-box; }}
body {{ background: #0a0a0a; width: 1920px; height: 1080px; overflow: hidden; font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; }}
canvas {{ display: block; width: 1920px; height: 1080px; }}
</style>
</head>
<body>
<canvas id="c" width="1920" height="1080"></canvas>
<script>
{js}
</script>
</body>
</html>
'''

with open('animation.html', 'w', encoding='utf-8') as f:
    f.write(html)

print(f'✓ Generated animation.html ({len(html)} bytes)')
print(f'  TOTAL_DURATION={TOTAL_DURATION}s')
print(f'  TIMING array has {len(TIMING)} segments')
